import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/CategoryList"
import NavigationBar from "@/components/NavigationBar/NavigationBar";
import Image from "next/image";
import SettingsSideBar from "@/components/SettingsPanel/SettingsSideBar";
import DuaSection from "@/components/DuaContent/DuaSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[#E2E2E2] grid grid-cols-12 gap-6 py-12 px-[20px]">
          <div className="col-span-1">
            <NavigationBar />
          </div>
          <div className="col-span-9">
            {/* title and search bar */}
            <div className="flex justify-between items-center mb-6">
              <h1 className="text-[24px] mt-2 font-semibold">Dua Page</h1>
              <div className="bg-white border-2 border-[#E2E2E2] rounded-[7px] flex">
                <input className='w-[297px] p-[13px]' placeholder='Search by Dua Name' type="text" />
                <Image src="/search.png" width={54} height={44} alt="img" />
              </div>
            </div>
            <div className="flex gap-6">
              <Sidebar />
              <div className="w-full">
                {children}
              </div>
            </div>
          </div>
          <div className="col-span-2">
            <div>
              {/* user icon */}
              <div className="max-w-[330px] flex  justify-end mb-8 mx-auto">
                <Image src="/Group_174.png" width={67} height={45} alt="img" />
              </div>
              <div>
                <SettingsSideBar />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
